version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: metrics_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -p 5433
    network_mode: host

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@127.0.0.1:5433/metrics_db
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    network_mode: host
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    network_mode: host

  stalwart:
    image: stalwartlabs/stalwart:latest
    container_name: stalwart
    restart: always
    environment:
      - STALWART_ADMIN_PASSWORD=${MAIL_ADMIN_PASS}
    volumes:
      - stalwart_data:/opt/stalwart-mail
    network_mode: host

volumes:
  postgres_data:
  redis_data:
  stalwart_data:
